name: Build and deploy in remote host 

on:
  push:
    branches:
      - main
     
  pull_request:
      types: [opened, synchronize, reopened]
 
jobs:
  webapp-build:
    runs-on: ubuntu-latest
     
    steps:  
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarqube.astrazeneca.com"
        
#     - name: Sleep for 300 seconds 
#       run: |
#          sleep 300s
        
#     - name: SonarQube Quality Gate check
#       id: sonarqube-quality-gate-check
#       uses: sonarsource/sonarqube-quality-gate-action@master
#       # Force to fail step after specific time.
#       timeout-minutes: 100
#       env:
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Build WAR with Maven
      shell: bash
      run: |
        mvn clean package
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker-Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                       
    - name: Build and push docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mywebapp:${{ github.sha }}
   
   
  webapp-deploy:
    needs: webapp-build
    runs-on: ubuntu-latest 
    steps:
    - name: Deploying in remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 8081:8080 --name my_webapp_container ${{ secrets.DOCKER_HUB_USERNAME }}/mywebapp:${{ github.sha }}
          docker ps
          sleep 100
          curl http://localhost:8081/demo/
