name: Build and deploy web app using github runner

on:
  push:
    branches:
      - main
     
  pull_request:
      types: [opened, synchronize, reopened]
 
jobs:
  webapp-deployment:
    runs-on: ubuntu-latest
     
    steps:  
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    # - name: SonarQube Scan
    #   uses: sonarsource/sonarqube-scan-action@master
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: "https://sonarqube.astrazeneca.com"
    
    #  - name: Sleep for 300 seconds 
    #    run: |
    #    sleep 300s
        
    # - name: SonarQube Quality Gate check
    #   id: sonarqube-quality-gate-check
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   # Force to fail step after specific time.
    #   timeout-minutes: 25
    #   env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Build WAR with Maven
      shell: bash
      run: |
        mvn clean package
        
    - name: Build docker image
      shell: bash
      run: |
        docker build -t mywebapp .  
        docker images
        
    - name: Deploy the webapp
      shell: bash
      run: |
        docker run -d -p 8081:8080 --name my_webapp_container mywebapp
        docker ps
        sleep 100
        curl http://127.0.0.1:8081/demo/
     # docker exec my_webapp_container curl http://localhost:8081/demo/      
        
        
   
